version: "3.8"

services:
  mlflow_db:
    image: postgres:latest
    container_name: mlflow_db
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data

  mlflow_server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    depends_on:
      - mlflow_db
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@mlflow_db:5432/mlflow_db
      - MLFLOW_ARTIFACT_STORE=/mlruns
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri postgresql://mlflow:mlflow@mlflow_db:5432/mlflow_db --host 0.0.0.0 --port 5000

  housing-model:
    build: .
    container_name: housing_model_container
    depends_on:
      - mlflow_server
    ports:
      - "8001:8001"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    command: >
      sh -c "
      python train_model.py &&
      uvicorn predict_api:app --host 0.0.0.0 --port 8001
      "

volumes:
  mlflow_db_data:
