FROM python:3.12

# Install MLflow
RUN pip install mlflow

# Expose port 5000 for the MLflow UI
EXPOSE 5000

# Start the MLflow UI
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./mlruns", "--host", "0.0.0.0", "--port", "5000"]