# Dockerfile

# Utiliser une image Python officielle comme base
FROM python:3.11-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y build-essential libpq-dev

# Copier les fichiers nécessaires pour Poetry
COPY pyproject.toml poetry.lock README.md ./

# Copier le dossier app avant d'installer les dépendances
COPY app/ app/

# Installer Poetry
RUN pip install --upgrade pip
RUN pip install poetry

# Configurer Poetry pour ne pas créer d'environnements virtuels
RUN poetry config virtualenvs.create false

# Installer les dépendances du projet
RUN poetry install --no-interaction --no-ansi

# Copier le reste des fichiers du projet
COPY . .

# Debug : Lister les fichiers pour vérifier que tout est présent
RUN ls -la /app
RUN ls -la /app/app

# Exposer le port de l'application
EXPOSE 8001

# Commande pour lancer l'application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
